# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oip_api_server.models.base_model_ import Model
from oip_api_server.models.position import Position  # noqa: F401,E501
from oip_api_server import util


class AccountingDocument(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, document_type: str=None, ledger_entry_no: int=None, fapiao_no: str=None, customer_no: int=None, company: str=None, posting_date: date=None, document_no: str=None, description: str=None, amount_currency_code: str=None, local_currency_code: str=None, foreign_currency_code: str=None, original_amount_net: float=None, original_amount_vat: float=None, original_amount_gross: float=None, original_local_amount_gross: float=None, original_foreign_amount_gross: float=None, remaining_amount_net: float=None, remaining_amount_vat: float=None, remaining_amount_gross: float=None, remaining_local_amount_gross: float=None, remaining_foreign_amount_gross: float=None, invoice_exchange_rate: float=None, debitor_currency_rate: float=None, exchange_rate: float=None, open: bool=None, confirmed: bool=None, salesperson_code: str=None, orig_number_of_nights: int=None, invoice_address_line1: str=None, invoice_address_line2: str=None, invoice_address_city: str=None, invoice_address_contact_no: str=None, invoice_address_country_region_code: str=None, invoice_address_customer_no: str=None, invoice_address_email: str=None, invoice_address_name: str=None, invoice_address_name2: str=None, invoice_address_post_code: str=None, hotel_address_line1: str=None, hotel_address_line2: str=None, hotel_address_city: str=None, hotel_address_country_region_code: str=None, hotel_address_name: str=None, hotel_address_name2: str=None, hotel_address_post_code: str=None, correction_from_document_no: str=None, document_date: date=None, external_document_no: str=None, has_pdf: bool=None, positions: List[Position]=None):  # noqa: E501
        """AccountingDocument - a model defined in Swagger

        :param document_type: The document_type of this AccountingDocument.  # noqa: E501
        :type document_type: str
        :param ledger_entry_no: The ledger_entry_no of this AccountingDocument.  # noqa: E501
        :type ledger_entry_no: int
        :param fapiao_no: The fapiao_no of this AccountingDocument.  # noqa: E501
        :type fapiao_no: str
        :param customer_no: The customer_no of this AccountingDocument.  # noqa: E501
        :type customer_no: int
        :param company: The company of this AccountingDocument.  # noqa: E501
        :type company: str
        :param posting_date: The posting_date of this AccountingDocument.  # noqa: E501
        :type posting_date: date
        :param document_no: The document_no of this AccountingDocument.  # noqa: E501
        :type document_no: str
        :param description: The description of this AccountingDocument.  # noqa: E501
        :type description: str
        :param amount_currency_code: The amount_currency_code of this AccountingDocument.  # noqa: E501
        :type amount_currency_code: str
        :param local_currency_code: The local_currency_code of this AccountingDocument.  # noqa: E501
        :type local_currency_code: str
        :param foreign_currency_code: The foreign_currency_code of this AccountingDocument.  # noqa: E501
        :type foreign_currency_code: str
        :param original_amount_net: The original_amount_net of this AccountingDocument.  # noqa: E501
        :type original_amount_net: float
        :param original_amount_vat: The original_amount_vat of this AccountingDocument.  # noqa: E501
        :type original_amount_vat: float
        :param original_amount_gross: The original_amount_gross of this AccountingDocument.  # noqa: E501
        :type original_amount_gross: float
        :param original_local_amount_gross: The original_local_amount_gross of this AccountingDocument.  # noqa: E501
        :type original_local_amount_gross: float
        :param original_foreign_amount_gross: The original_foreign_amount_gross of this AccountingDocument.  # noqa: E501
        :type original_foreign_amount_gross: float
        :param remaining_amount_net: The remaining_amount_net of this AccountingDocument.  # noqa: E501
        :type remaining_amount_net: float
        :param remaining_amount_vat: The remaining_amount_vat of this AccountingDocument.  # noqa: E501
        :type remaining_amount_vat: float
        :param remaining_amount_gross: The remaining_amount_gross of this AccountingDocument.  # noqa: E501
        :type remaining_amount_gross: float
        :param remaining_local_amount_gross: The remaining_local_amount_gross of this AccountingDocument.  # noqa: E501
        :type remaining_local_amount_gross: float
        :param remaining_foreign_amount_gross: The remaining_foreign_amount_gross of this AccountingDocument.  # noqa: E501
        :type remaining_foreign_amount_gross: float
        :param invoice_exchange_rate: The invoice_exchange_rate of this AccountingDocument.  # noqa: E501
        :type invoice_exchange_rate: float
        :param debitor_currency_rate: The debitor_currency_rate of this AccountingDocument.  # noqa: E501
        :type debitor_currency_rate: float
        :param exchange_rate: The exchange_rate of this AccountingDocument.  # noqa: E501
        :type exchange_rate: float
        :param open: The open of this AccountingDocument.  # noqa: E501
        :type open: bool
        :param confirmed: The confirmed of this AccountingDocument.  # noqa: E501
        :type confirmed: bool
        :param salesperson_code: The salesperson_code of this AccountingDocument.  # noqa: E501
        :type salesperson_code: str
        :param orig_number_of_nights: The orig_number_of_nights of this AccountingDocument.  # noqa: E501
        :type orig_number_of_nights: int
        :param invoice_address_line1: The invoice_address_line1 of this AccountingDocument.  # noqa: E501
        :type invoice_address_line1: str
        :param invoice_address_line2: The invoice_address_line2 of this AccountingDocument.  # noqa: E501
        :type invoice_address_line2: str
        :param invoice_address_city: The invoice_address_city of this AccountingDocument.  # noqa: E501
        :type invoice_address_city: str
        :param invoice_address_contact_no: The invoice_address_contact_no of this AccountingDocument.  # noqa: E501
        :type invoice_address_contact_no: str
        :param invoice_address_country_region_code: The invoice_address_country_region_code of this AccountingDocument.  # noqa: E501
        :type invoice_address_country_region_code: str
        :param invoice_address_customer_no: The invoice_address_customer_no of this AccountingDocument.  # noqa: E501
        :type invoice_address_customer_no: str
        :param invoice_address_email: The invoice_address_email of this AccountingDocument.  # noqa: E501
        :type invoice_address_email: str
        :param invoice_address_name: The invoice_address_name of this AccountingDocument.  # noqa: E501
        :type invoice_address_name: str
        :param invoice_address_name2: The invoice_address_name2 of this AccountingDocument.  # noqa: E501
        :type invoice_address_name2: str
        :param invoice_address_post_code: The invoice_address_post_code of this AccountingDocument.  # noqa: E501
        :type invoice_address_post_code: str
        :param hotel_address_line1: The hotel_address_line1 of this AccountingDocument.  # noqa: E501
        :type hotel_address_line1: str
        :param hotel_address_line2: The hotel_address_line2 of this AccountingDocument.  # noqa: E501
        :type hotel_address_line2: str
        :param hotel_address_city: The hotel_address_city of this AccountingDocument.  # noqa: E501
        :type hotel_address_city: str
        :param hotel_address_country_region_code: The hotel_address_country_region_code of this AccountingDocument.  # noqa: E501
        :type hotel_address_country_region_code: str
        :param hotel_address_name: The hotel_address_name of this AccountingDocument.  # noqa: E501
        :type hotel_address_name: str
        :param hotel_address_name2: The hotel_address_name2 of this AccountingDocument.  # noqa: E501
        :type hotel_address_name2: str
        :param hotel_address_post_code: The hotel_address_post_code of this AccountingDocument.  # noqa: E501
        :type hotel_address_post_code: str
        :param correction_from_document_no: The correction_from_document_no of this AccountingDocument.  # noqa: E501
        :type correction_from_document_no: str
        :param document_date: The document_date of this AccountingDocument.  # noqa: E501
        :type document_date: date
        :param external_document_no: The external_document_no of this AccountingDocument.  # noqa: E501
        :type external_document_no: str
        :param has_pdf: The has_pdf of this AccountingDocument.  # noqa: E501
        :type has_pdf: bool
        :param positions: The positions of this AccountingDocument.  # noqa: E501
        :type positions: List[Position]
        """
        self.swagger_types = {
            'document_type': str,
            'ledger_entry_no': int,
            'fapiao_no': str,
            'customer_no': int,
            'company': str,
            'posting_date': date,
            'document_no': str,
            'description': str,
            'amount_currency_code': str,
            'local_currency_code': str,
            'foreign_currency_code': str,
            'original_amount_net': float,
            'original_amount_vat': float,
            'original_amount_gross': float,
            'original_local_amount_gross': float,
            'original_foreign_amount_gross': float,
            'remaining_amount_net': float,
            'remaining_amount_vat': float,
            'remaining_amount_gross': float,
            'remaining_local_amount_gross': float,
            'remaining_foreign_amount_gross': float,
            'invoice_exchange_rate': float,
            'debitor_currency_rate': float,
            'exchange_rate': float,
            'open': bool,
            'confirmed': bool,
            'salesperson_code': str,
            'orig_number_of_nights': int,
            'invoice_address_line1': str,
            'invoice_address_line2': str,
            'invoice_address_city': str,
            'invoice_address_contact_no': str,
            'invoice_address_country_region_code': str,
            'invoice_address_customer_no': str,
            'invoice_address_email': str,
            'invoice_address_name': str,
            'invoice_address_name2': str,
            'invoice_address_post_code': str,
            'hotel_address_line1': str,
            'hotel_address_line2': str,
            'hotel_address_city': str,
            'hotel_address_country_region_code': str,
            'hotel_address_name': str,
            'hotel_address_name2': str,
            'hotel_address_post_code': str,
            'correction_from_document_no': str,
            'document_date': date,
            'external_document_no': str,
            'has_pdf': bool,
            'positions': List[Position]
        }

        self.attribute_map = {
            'document_type': 'DocumentType',
            'ledger_entry_no': 'LedgerEntryNo',
            'fapiao_no': 'FapiaoNo',
            'customer_no': 'CustomerNo',
            'company': 'Company',
            'posting_date': 'PostingDate',
            'document_no': 'DocumentNo',
            'description': 'Description',
            'amount_currency_code': 'AmountCurrencyCode',
            'local_currency_code': 'LocalCurrencyCode',
            'foreign_currency_code': 'ForeignCurrencyCode',
            'original_amount_net': 'OriginalAmountNet',
            'original_amount_vat': 'OriginalAmountVAT',
            'original_amount_gross': 'OriginalAmountGross',
            'original_local_amount_gross': 'OriginalLocalAmountGross',
            'original_foreign_amount_gross': 'OriginalForeignAmountGross',
            'remaining_amount_net': 'RemainingAmountNet',
            'remaining_amount_vat': 'RemainingAmountVAT',
            'remaining_amount_gross': 'RemainingAmountGross',
            'remaining_local_amount_gross': 'RemainingLocalAmountGross',
            'remaining_foreign_amount_gross': 'RemainingForeignAmountGross',
            'invoice_exchange_rate': 'InvoiceExchangeRate',
            'debitor_currency_rate': 'DebitorCurrencyRate',
            'exchange_rate': 'ExchangeRate',
            'open': 'Open',
            'confirmed': 'Confirmed',
            'salesperson_code': 'SalespersonCode',
            'orig_number_of_nights': 'OrigNumberOfNights',
            'invoice_address_line1': 'InvoiceAddressLine1',
            'invoice_address_line2': 'InvoiceAddressLine2',
            'invoice_address_city': 'InvoiceAddressCity',
            'invoice_address_contact_no': 'InvoiceAddressContactNo',
            'invoice_address_country_region_code': 'InvoiceAddressCountryRegionCode',
            'invoice_address_customer_no': 'InvoiceAddressCustomerNo',
            'invoice_address_email': 'InvoiceAddressEmail',
            'invoice_address_name': 'InvoiceAddressName',
            'invoice_address_name2': 'InvoiceAddressName2',
            'invoice_address_post_code': 'InvoiceAddressPostCode',
            'hotel_address_line1': 'HotelAddressLine1',
            'hotel_address_line2': 'HotelAddressLine2',
            'hotel_address_city': 'HotelAddressCity',
            'hotel_address_country_region_code': 'HotelAddressCountryRegionCode',
            'hotel_address_name': 'HotelAddressName',
            'hotel_address_name2': 'HotelAddressName2',
            'hotel_address_post_code': 'HotelAddressPostCode',
            'correction_from_document_no': 'CorrectionFromDocumentNo',
            'document_date': 'DocumentDate',
            'external_document_no': 'ExternalDocumentNo',
            'has_pdf': 'HasPdf',
            'positions': 'Positions'
        }
        self._document_type = document_type
        self._ledger_entry_no = ledger_entry_no
        self._fapiao_no = fapiao_no
        self._customer_no = customer_no
        self._company = company
        self._posting_date = posting_date
        self._document_no = document_no
        self._description = description
        self._amount_currency_code = amount_currency_code
        self._local_currency_code = local_currency_code
        self._foreign_currency_code = foreign_currency_code
        self._original_amount_net = original_amount_net
        self._original_amount_vat = original_amount_vat
        self._original_amount_gross = original_amount_gross
        self._original_local_amount_gross = original_local_amount_gross
        self._original_foreign_amount_gross = original_foreign_amount_gross
        self._remaining_amount_net = remaining_amount_net
        self._remaining_amount_vat = remaining_amount_vat
        self._remaining_amount_gross = remaining_amount_gross
        self._remaining_local_amount_gross = remaining_local_amount_gross
        self._remaining_foreign_amount_gross = remaining_foreign_amount_gross
        self._invoice_exchange_rate = invoice_exchange_rate
        self._debitor_currency_rate = debitor_currency_rate
        self._exchange_rate = exchange_rate
        self._open = open
        self._confirmed = confirmed
        self._salesperson_code = salesperson_code
        self._orig_number_of_nights = orig_number_of_nights
        self._invoice_address_line1 = invoice_address_line1
        self._invoice_address_line2 = invoice_address_line2
        self._invoice_address_city = invoice_address_city
        self._invoice_address_contact_no = invoice_address_contact_no
        self._invoice_address_country_region_code = invoice_address_country_region_code
        self._invoice_address_customer_no = invoice_address_customer_no
        self._invoice_address_email = invoice_address_email
        self._invoice_address_name = invoice_address_name
        self._invoice_address_name2 = invoice_address_name2
        self._invoice_address_post_code = invoice_address_post_code
        self._hotel_address_line1 = hotel_address_line1
        self._hotel_address_line2 = hotel_address_line2
        self._hotel_address_city = hotel_address_city
        self._hotel_address_country_region_code = hotel_address_country_region_code
        self._hotel_address_name = hotel_address_name
        self._hotel_address_name2 = hotel_address_name2
        self._hotel_address_post_code = hotel_address_post_code
        self._correction_from_document_no = correction_from_document_no
        self._document_date = document_date
        self._external_document_no = external_document_no
        self._has_pdf = has_pdf
        self._positions = positions

    @classmethod
    def from_dict(cls, dikt) -> 'AccountingDocument':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccountingDocument of this AccountingDocument.  # noqa: E501
        :rtype: AccountingDocument
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document_type(self) -> str:
        """Gets the document_type of this AccountingDocument.


        :return: The document_type of this AccountingDocument.
        :rtype: str
        """
        return self._document_type

    @document_type.setter
    def document_type(self, document_type: str):
        """Sets the document_type of this AccountingDocument.


        :param document_type: The document_type of this AccountingDocument.
        :type document_type: str
        """
        allowed_values = ["Payment", "Subseq. Deb. Invoice", "Fapiao", "Commission Invoice", "Booking Overview", "Debit Collection Invoice", "Refund Invoice", "Marketplace Fee", "Sourcing Fee", "Marketing Invoice", "Invoice", "Credit Memo", "Finance Charge Memo", "Reminder", "Refund"]  # noqa: E501
        if document_type not in allowed_values:
            raise ValueError(
                "Invalid value for `document_type` ({0}), must be one of {1}"
                .format(document_type, allowed_values)
            )

        self._document_type = document_type

    @property
    def ledger_entry_no(self) -> int:
        """Gets the ledger_entry_no of this AccountingDocument.

        Number of Customer Ledger Entry  # noqa: E501

        :return: The ledger_entry_no of this AccountingDocument.
        :rtype: int
        """
        return self._ledger_entry_no

    @ledger_entry_no.setter
    def ledger_entry_no(self, ledger_entry_no: int):
        """Sets the ledger_entry_no of this AccountingDocument.

        Number of Customer Ledger Entry  # noqa: E501

        :param ledger_entry_no: The ledger_entry_no of this AccountingDocument.
        :type ledger_entry_no: int
        """
        if ledger_entry_no is None:
            raise ValueError("Invalid value for `ledger_entry_no`, must not be `None`")  # noqa: E501

        self._ledger_entry_no = ledger_entry_no

    @property
    def fapiao_no(self) -> str:
        """Gets the fapiao_no of this AccountingDocument.


        :return: The fapiao_no of this AccountingDocument.
        :rtype: str
        """
        return self._fapiao_no

    @fapiao_no.setter
    def fapiao_no(self, fapiao_no: str):
        """Sets the fapiao_no of this AccountingDocument.


        :param fapiao_no: The fapiao_no of this AccountingDocument.
        :type fapiao_no: str
        """

        self._fapiao_no = fapiao_no

    @property
    def customer_no(self) -> int:
        """Gets the customer_no of this AccountingDocument.


        :return: The customer_no of this AccountingDocument.
        :rtype: int
        """
        return self._customer_no

    @customer_no.setter
    def customer_no(self, customer_no: int):
        """Sets the customer_no of this AccountingDocument.


        :param customer_no: The customer_no of this AccountingDocument.
        :type customer_no: int
        """
        if customer_no is None:
            raise ValueError("Invalid value for `customer_no`, must not be `None`")  # noqa: E501

        self._customer_no = customer_no

    @property
    def company(self) -> str:
        """Gets the company of this AccountingDocument.


        :return: The company of this AccountingDocument.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company: str):
        """Sets the company of this AccountingDocument.


        :param company: The company of this AccountingDocument.
        :type company: str
        """
        if company is None:
            raise ValueError("Invalid value for `company`, must not be `None`")  # noqa: E501

        self._company = company

    @property
    def posting_date(self) -> date:
        """Gets the posting_date of this AccountingDocument.


        :return: The posting_date of this AccountingDocument.
        :rtype: date
        """
        return self._posting_date

    @posting_date.setter
    def posting_date(self, posting_date: date):
        """Sets the posting_date of this AccountingDocument.


        :param posting_date: The posting_date of this AccountingDocument.
        :type posting_date: date
        """
        if posting_date is None:
            raise ValueError("Invalid value for `posting_date`, must not be `None`")  # noqa: E501

        self._posting_date = posting_date

    @property
    def document_no(self) -> str:
        """Gets the document_no of this AccountingDocument.


        :return: The document_no of this AccountingDocument.
        :rtype: str
        """
        return self._document_no

    @document_no.setter
    def document_no(self, document_no: str):
        """Sets the document_no of this AccountingDocument.


        :param document_no: The document_no of this AccountingDocument.
        :type document_no: str
        """
        if document_no is None:
            raise ValueError("Invalid value for `document_no`, must not be `None`")  # noqa: E501

        self._document_no = document_no

    @property
    def description(self) -> str:
        """Gets the description of this AccountingDocument.


        :return: The description of this AccountingDocument.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this AccountingDocument.


        :param description: The description of this AccountingDocument.
        :type description: str
        """

        self._description = description

    @property
    def amount_currency_code(self) -> str:
        """Gets the amount_currency_code of this AccountingDocument.


        :return: The amount_currency_code of this AccountingDocument.
        :rtype: str
        """
        return self._amount_currency_code

    @amount_currency_code.setter
    def amount_currency_code(self, amount_currency_code: str):
        """Sets the amount_currency_code of this AccountingDocument.


        :param amount_currency_code: The amount_currency_code of this AccountingDocument.
        :type amount_currency_code: str
        """
        if amount_currency_code is None:
            raise ValueError("Invalid value for `amount_currency_code`, must not be `None`")  # noqa: E501

        self._amount_currency_code = amount_currency_code

    @property
    def local_currency_code(self) -> str:
        """Gets the local_currency_code of this AccountingDocument.


        :return: The local_currency_code of this AccountingDocument.
        :rtype: str
        """
        return self._local_currency_code

    @local_currency_code.setter
    def local_currency_code(self, local_currency_code: str):
        """Sets the local_currency_code of this AccountingDocument.


        :param local_currency_code: The local_currency_code of this AccountingDocument.
        :type local_currency_code: str
        """
        if local_currency_code is None:
            raise ValueError("Invalid value for `local_currency_code`, must not be `None`")  # noqa: E501

        self._local_currency_code = local_currency_code

    @property
    def foreign_currency_code(self) -> str:
        """Gets the foreign_currency_code of this AccountingDocument.


        :return: The foreign_currency_code of this AccountingDocument.
        :rtype: str
        """
        return self._foreign_currency_code

    @foreign_currency_code.setter
    def foreign_currency_code(self, foreign_currency_code: str):
        """Sets the foreign_currency_code of this AccountingDocument.


        :param foreign_currency_code: The foreign_currency_code of this AccountingDocument.
        :type foreign_currency_code: str
        """
        if foreign_currency_code is None:
            raise ValueError("Invalid value for `foreign_currency_code`, must not be `None`")  # noqa: E501

        self._foreign_currency_code = foreign_currency_code

    @property
    def original_amount_net(self) -> float:
        """Gets the original_amount_net of this AccountingDocument.


        :return: The original_amount_net of this AccountingDocument.
        :rtype: float
        """
        return self._original_amount_net

    @original_amount_net.setter
    def original_amount_net(self, original_amount_net: float):
        """Sets the original_amount_net of this AccountingDocument.


        :param original_amount_net: The original_amount_net of this AccountingDocument.
        :type original_amount_net: float
        """
        if original_amount_net is None:
            raise ValueError("Invalid value for `original_amount_net`, must not be `None`")  # noqa: E501

        self._original_amount_net = original_amount_net

    @property
    def original_amount_vat(self) -> float:
        """Gets the original_amount_vat of this AccountingDocument.


        :return: The original_amount_vat of this AccountingDocument.
        :rtype: float
        """
        return self._original_amount_vat

    @original_amount_vat.setter
    def original_amount_vat(self, original_amount_vat: float):
        """Sets the original_amount_vat of this AccountingDocument.


        :param original_amount_vat: The original_amount_vat of this AccountingDocument.
        :type original_amount_vat: float
        """
        if original_amount_vat is None:
            raise ValueError("Invalid value for `original_amount_vat`, must not be `None`")  # noqa: E501

        self._original_amount_vat = original_amount_vat

    @property
    def original_amount_gross(self) -> float:
        """Gets the original_amount_gross of this AccountingDocument.


        :return: The original_amount_gross of this AccountingDocument.
        :rtype: float
        """
        return self._original_amount_gross

    @original_amount_gross.setter
    def original_amount_gross(self, original_amount_gross: float):
        """Sets the original_amount_gross of this AccountingDocument.


        :param original_amount_gross: The original_amount_gross of this AccountingDocument.
        :type original_amount_gross: float
        """
        if original_amount_gross is None:
            raise ValueError("Invalid value for `original_amount_gross`, must not be `None`")  # noqa: E501

        self._original_amount_gross = original_amount_gross

    @property
    def original_local_amount_gross(self) -> float:
        """Gets the original_local_amount_gross of this AccountingDocument.


        :return: The original_local_amount_gross of this AccountingDocument.
        :rtype: float
        """
        return self._original_local_amount_gross

    @original_local_amount_gross.setter
    def original_local_amount_gross(self, original_local_amount_gross: float):
        """Sets the original_local_amount_gross of this AccountingDocument.


        :param original_local_amount_gross: The original_local_amount_gross of this AccountingDocument.
        :type original_local_amount_gross: float
        """
        if original_local_amount_gross is None:
            raise ValueError("Invalid value for `original_local_amount_gross`, must not be `None`")  # noqa: E501

        self._original_local_amount_gross = original_local_amount_gross

    @property
    def original_foreign_amount_gross(self) -> float:
        """Gets the original_foreign_amount_gross of this AccountingDocument.


        :return: The original_foreign_amount_gross of this AccountingDocument.
        :rtype: float
        """
        return self._original_foreign_amount_gross

    @original_foreign_amount_gross.setter
    def original_foreign_amount_gross(self, original_foreign_amount_gross: float):
        """Sets the original_foreign_amount_gross of this AccountingDocument.


        :param original_foreign_amount_gross: The original_foreign_amount_gross of this AccountingDocument.
        :type original_foreign_amount_gross: float
        """
        if original_foreign_amount_gross is None:
            raise ValueError("Invalid value for `original_foreign_amount_gross`, must not be `None`")  # noqa: E501

        self._original_foreign_amount_gross = original_foreign_amount_gross

    @property
    def remaining_amount_net(self) -> float:
        """Gets the remaining_amount_net of this AccountingDocument.


        :return: The remaining_amount_net of this AccountingDocument.
        :rtype: float
        """
        return self._remaining_amount_net

    @remaining_amount_net.setter
    def remaining_amount_net(self, remaining_amount_net: float):
        """Sets the remaining_amount_net of this AccountingDocument.


        :param remaining_amount_net: The remaining_amount_net of this AccountingDocument.
        :type remaining_amount_net: float
        """
        if remaining_amount_net is None:
            raise ValueError("Invalid value for `remaining_amount_net`, must not be `None`")  # noqa: E501

        self._remaining_amount_net = remaining_amount_net

    @property
    def remaining_amount_vat(self) -> float:
        """Gets the remaining_amount_vat of this AccountingDocument.


        :return: The remaining_amount_vat of this AccountingDocument.
        :rtype: float
        """
        return self._remaining_amount_vat

    @remaining_amount_vat.setter
    def remaining_amount_vat(self, remaining_amount_vat: float):
        """Sets the remaining_amount_vat of this AccountingDocument.


        :param remaining_amount_vat: The remaining_amount_vat of this AccountingDocument.
        :type remaining_amount_vat: float
        """
        if remaining_amount_vat is None:
            raise ValueError("Invalid value for `remaining_amount_vat`, must not be `None`")  # noqa: E501

        self._remaining_amount_vat = remaining_amount_vat

    @property
    def remaining_amount_gross(self) -> float:
        """Gets the remaining_amount_gross of this AccountingDocument.


        :return: The remaining_amount_gross of this AccountingDocument.
        :rtype: float
        """
        return self._remaining_amount_gross

    @remaining_amount_gross.setter
    def remaining_amount_gross(self, remaining_amount_gross: float):
        """Sets the remaining_amount_gross of this AccountingDocument.


        :param remaining_amount_gross: The remaining_amount_gross of this AccountingDocument.
        :type remaining_amount_gross: float
        """
        if remaining_amount_gross is None:
            raise ValueError("Invalid value for `remaining_amount_gross`, must not be `None`")  # noqa: E501

        self._remaining_amount_gross = remaining_amount_gross

    @property
    def remaining_local_amount_gross(self) -> float:
        """Gets the remaining_local_amount_gross of this AccountingDocument.


        :return: The remaining_local_amount_gross of this AccountingDocument.
        :rtype: float
        """
        return self._remaining_local_amount_gross

    @remaining_local_amount_gross.setter
    def remaining_local_amount_gross(self, remaining_local_amount_gross: float):
        """Sets the remaining_local_amount_gross of this AccountingDocument.


        :param remaining_local_amount_gross: The remaining_local_amount_gross of this AccountingDocument.
        :type remaining_local_amount_gross: float
        """
        if remaining_local_amount_gross is None:
            raise ValueError("Invalid value for `remaining_local_amount_gross`, must not be `None`")  # noqa: E501

        self._remaining_local_amount_gross = remaining_local_amount_gross

    @property
    def remaining_foreign_amount_gross(self) -> float:
        """Gets the remaining_foreign_amount_gross of this AccountingDocument.


        :return: The remaining_foreign_amount_gross of this AccountingDocument.
        :rtype: float
        """
        return self._remaining_foreign_amount_gross

    @remaining_foreign_amount_gross.setter
    def remaining_foreign_amount_gross(self, remaining_foreign_amount_gross: float):
        """Sets the remaining_foreign_amount_gross of this AccountingDocument.


        :param remaining_foreign_amount_gross: The remaining_foreign_amount_gross of this AccountingDocument.
        :type remaining_foreign_amount_gross: float
        """
        if remaining_foreign_amount_gross is None:
            raise ValueError("Invalid value for `remaining_foreign_amount_gross`, must not be `None`")  # noqa: E501

        self._remaining_foreign_amount_gross = remaining_foreign_amount_gross

    @property
    def invoice_exchange_rate(self) -> float:
        """Gets the invoice_exchange_rate of this AccountingDocument.


        :return: The invoice_exchange_rate of this AccountingDocument.
        :rtype: float
        """
        return self._invoice_exchange_rate

    @invoice_exchange_rate.setter
    def invoice_exchange_rate(self, invoice_exchange_rate: float):
        """Sets the invoice_exchange_rate of this AccountingDocument.


        :param invoice_exchange_rate: The invoice_exchange_rate of this AccountingDocument.
        :type invoice_exchange_rate: float
        """
        if invoice_exchange_rate is None:
            raise ValueError("Invalid value for `invoice_exchange_rate`, must not be `None`")  # noqa: E501

        self._invoice_exchange_rate = invoice_exchange_rate

    @property
    def debitor_currency_rate(self) -> float:
        """Gets the debitor_currency_rate of this AccountingDocument.


        :return: The debitor_currency_rate of this AccountingDocument.
        :rtype: float
        """
        return self._debitor_currency_rate

    @debitor_currency_rate.setter
    def debitor_currency_rate(self, debitor_currency_rate: float):
        """Sets the debitor_currency_rate of this AccountingDocument.


        :param debitor_currency_rate: The debitor_currency_rate of this AccountingDocument.
        :type debitor_currency_rate: float
        """
        if debitor_currency_rate is None:
            raise ValueError("Invalid value for `debitor_currency_rate`, must not be `None`")  # noqa: E501

        self._debitor_currency_rate = debitor_currency_rate

    @property
    def exchange_rate(self) -> float:
        """Gets the exchange_rate of this AccountingDocument.


        :return: The exchange_rate of this AccountingDocument.
        :rtype: float
        """
        return self._exchange_rate

    @exchange_rate.setter
    def exchange_rate(self, exchange_rate: float):
        """Sets the exchange_rate of this AccountingDocument.


        :param exchange_rate: The exchange_rate of this AccountingDocument.
        :type exchange_rate: float
        """
        if exchange_rate is None:
            raise ValueError("Invalid value for `exchange_rate`, must not be `None`")  # noqa: E501

        self._exchange_rate = exchange_rate

    @property
    def open(self) -> bool:
        """Gets the open of this AccountingDocument.


        :return: The open of this AccountingDocument.
        :rtype: bool
        """
        return self._open

    @open.setter
    def open(self, open: bool):
        """Sets the open of this AccountingDocument.


        :param open: The open of this AccountingDocument.
        :type open: bool
        """
        if open is None:
            raise ValueError("Invalid value for `open`, must not be `None`")  # noqa: E501

        self._open = open

    @property
    def confirmed(self) -> bool:
        """Gets the confirmed of this AccountingDocument.


        :return: The confirmed of this AccountingDocument.
        :rtype: bool
        """
        return self._confirmed

    @confirmed.setter
    def confirmed(self, confirmed: bool):
        """Sets the confirmed of this AccountingDocument.


        :param confirmed: The confirmed of this AccountingDocument.
        :type confirmed: bool
        """
        if confirmed is None:
            raise ValueError("Invalid value for `confirmed`, must not be `None`")  # noqa: E501

        self._confirmed = confirmed

    @property
    def salesperson_code(self) -> str:
        """Gets the salesperson_code of this AccountingDocument.


        :return: The salesperson_code of this AccountingDocument.
        :rtype: str
        """
        return self._salesperson_code

    @salesperson_code.setter
    def salesperson_code(self, salesperson_code: str):
        """Sets the salesperson_code of this AccountingDocument.


        :param salesperson_code: The salesperson_code of this AccountingDocument.
        :type salesperson_code: str
        """

        self._salesperson_code = salesperson_code

    @property
    def orig_number_of_nights(self) -> int:
        """Gets the orig_number_of_nights of this AccountingDocument.


        :return: The orig_number_of_nights of this AccountingDocument.
        :rtype: int
        """
        return self._orig_number_of_nights

    @orig_number_of_nights.setter
    def orig_number_of_nights(self, orig_number_of_nights: int):
        """Sets the orig_number_of_nights of this AccountingDocument.


        :param orig_number_of_nights: The orig_number_of_nights of this AccountingDocument.
        :type orig_number_of_nights: int
        """
        if orig_number_of_nights is None:
            raise ValueError("Invalid value for `orig_number_of_nights`, must not be `None`")  # noqa: E501

        self._orig_number_of_nights = orig_number_of_nights

    @property
    def invoice_address_line1(self) -> str:
        """Gets the invoice_address_line1 of this AccountingDocument.


        :return: The invoice_address_line1 of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_line1

    @invoice_address_line1.setter
    def invoice_address_line1(self, invoice_address_line1: str):
        """Sets the invoice_address_line1 of this AccountingDocument.


        :param invoice_address_line1: The invoice_address_line1 of this AccountingDocument.
        :type invoice_address_line1: str
        """
        if invoice_address_line1 is None:
            raise ValueError("Invalid value for `invoice_address_line1`, must not be `None`")  # noqa: E501

        self._invoice_address_line1 = invoice_address_line1

    @property
    def invoice_address_line2(self) -> str:
        """Gets the invoice_address_line2 of this AccountingDocument.


        :return: The invoice_address_line2 of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_line2

    @invoice_address_line2.setter
    def invoice_address_line2(self, invoice_address_line2: str):
        """Sets the invoice_address_line2 of this AccountingDocument.


        :param invoice_address_line2: The invoice_address_line2 of this AccountingDocument.
        :type invoice_address_line2: str
        """

        self._invoice_address_line2 = invoice_address_line2

    @property
    def invoice_address_city(self) -> str:
        """Gets the invoice_address_city of this AccountingDocument.


        :return: The invoice_address_city of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_city

    @invoice_address_city.setter
    def invoice_address_city(self, invoice_address_city: str):
        """Sets the invoice_address_city of this AccountingDocument.


        :param invoice_address_city: The invoice_address_city of this AccountingDocument.
        :type invoice_address_city: str
        """
        if invoice_address_city is None:
            raise ValueError("Invalid value for `invoice_address_city`, must not be `None`")  # noqa: E501

        self._invoice_address_city = invoice_address_city

    @property
    def invoice_address_contact_no(self) -> str:
        """Gets the invoice_address_contact_no of this AccountingDocument.


        :return: The invoice_address_contact_no of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_contact_no

    @invoice_address_contact_no.setter
    def invoice_address_contact_no(self, invoice_address_contact_no: str):
        """Sets the invoice_address_contact_no of this AccountingDocument.


        :param invoice_address_contact_no: The invoice_address_contact_no of this AccountingDocument.
        :type invoice_address_contact_no: str
        """
        if invoice_address_contact_no is None:
            raise ValueError("Invalid value for `invoice_address_contact_no`, must not be `None`")  # noqa: E501

        self._invoice_address_contact_no = invoice_address_contact_no

    @property
    def invoice_address_country_region_code(self) -> str:
        """Gets the invoice_address_country_region_code of this AccountingDocument.


        :return: The invoice_address_country_region_code of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_country_region_code

    @invoice_address_country_region_code.setter
    def invoice_address_country_region_code(self, invoice_address_country_region_code: str):
        """Sets the invoice_address_country_region_code of this AccountingDocument.


        :param invoice_address_country_region_code: The invoice_address_country_region_code of this AccountingDocument.
        :type invoice_address_country_region_code: str
        """
        if invoice_address_country_region_code is None:
            raise ValueError("Invalid value for `invoice_address_country_region_code`, must not be `None`")  # noqa: E501

        self._invoice_address_country_region_code = invoice_address_country_region_code

    @property
    def invoice_address_customer_no(self) -> str:
        """Gets the invoice_address_customer_no of this AccountingDocument.


        :return: The invoice_address_customer_no of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_customer_no

    @invoice_address_customer_no.setter
    def invoice_address_customer_no(self, invoice_address_customer_no: str):
        """Sets the invoice_address_customer_no of this AccountingDocument.


        :param invoice_address_customer_no: The invoice_address_customer_no of this AccountingDocument.
        :type invoice_address_customer_no: str
        """
        if invoice_address_customer_no is None:
            raise ValueError("Invalid value for `invoice_address_customer_no`, must not be `None`")  # noqa: E501

        self._invoice_address_customer_no = invoice_address_customer_no

    @property
    def invoice_address_email(self) -> str:
        """Gets the invoice_address_email of this AccountingDocument.


        :return: The invoice_address_email of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_email

    @invoice_address_email.setter
    def invoice_address_email(self, invoice_address_email: str):
        """Sets the invoice_address_email of this AccountingDocument.


        :param invoice_address_email: The invoice_address_email of this AccountingDocument.
        :type invoice_address_email: str
        """
        if invoice_address_email is None:
            raise ValueError("Invalid value for `invoice_address_email`, must not be `None`")  # noqa: E501

        self._invoice_address_email = invoice_address_email

    @property
    def invoice_address_name(self) -> str:
        """Gets the invoice_address_name of this AccountingDocument.


        :return: The invoice_address_name of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_name

    @invoice_address_name.setter
    def invoice_address_name(self, invoice_address_name: str):
        """Sets the invoice_address_name of this AccountingDocument.


        :param invoice_address_name: The invoice_address_name of this AccountingDocument.
        :type invoice_address_name: str
        """
        if invoice_address_name is None:
            raise ValueError("Invalid value for `invoice_address_name`, must not be `None`")  # noqa: E501

        self._invoice_address_name = invoice_address_name

    @property
    def invoice_address_name2(self) -> str:
        """Gets the invoice_address_name2 of this AccountingDocument.


        :return: The invoice_address_name2 of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_name2

    @invoice_address_name2.setter
    def invoice_address_name2(self, invoice_address_name2: str):
        """Sets the invoice_address_name2 of this AccountingDocument.


        :param invoice_address_name2: The invoice_address_name2 of this AccountingDocument.
        :type invoice_address_name2: str
        """

        self._invoice_address_name2 = invoice_address_name2

    @property
    def invoice_address_post_code(self) -> str:
        """Gets the invoice_address_post_code of this AccountingDocument.


        :return: The invoice_address_post_code of this AccountingDocument.
        :rtype: str
        """
        return self._invoice_address_post_code

    @invoice_address_post_code.setter
    def invoice_address_post_code(self, invoice_address_post_code: str):
        """Sets the invoice_address_post_code of this AccountingDocument.


        :param invoice_address_post_code: The invoice_address_post_code of this AccountingDocument.
        :type invoice_address_post_code: str
        """
        if invoice_address_post_code is None:
            raise ValueError("Invalid value for `invoice_address_post_code`, must not be `None`")  # noqa: E501

        self._invoice_address_post_code = invoice_address_post_code

    @property
    def hotel_address_line1(self) -> str:
        """Gets the hotel_address_line1 of this AccountingDocument.


        :return: The hotel_address_line1 of this AccountingDocument.
        :rtype: str
        """
        return self._hotel_address_line1

    @hotel_address_line1.setter
    def hotel_address_line1(self, hotel_address_line1: str):
        """Sets the hotel_address_line1 of this AccountingDocument.


        :param hotel_address_line1: The hotel_address_line1 of this AccountingDocument.
        :type hotel_address_line1: str
        """
        if hotel_address_line1 is None:
            raise ValueError("Invalid value for `hotel_address_line1`, must not be `None`")  # noqa: E501

        self._hotel_address_line1 = hotel_address_line1

    @property
    def hotel_address_line2(self) -> str:
        """Gets the hotel_address_line2 of this AccountingDocument.


        :return: The hotel_address_line2 of this AccountingDocument.
        :rtype: str
        """
        return self._hotel_address_line2

    @hotel_address_line2.setter
    def hotel_address_line2(self, hotel_address_line2: str):
        """Sets the hotel_address_line2 of this AccountingDocument.


        :param hotel_address_line2: The hotel_address_line2 of this AccountingDocument.
        :type hotel_address_line2: str
        """

        self._hotel_address_line2 = hotel_address_line2

    @property
    def hotel_address_city(self) -> str:
        """Gets the hotel_address_city of this AccountingDocument.


        :return: The hotel_address_city of this AccountingDocument.
        :rtype: str
        """
        return self._hotel_address_city

    @hotel_address_city.setter
    def hotel_address_city(self, hotel_address_city: str):
        """Sets the hotel_address_city of this AccountingDocument.


        :param hotel_address_city: The hotel_address_city of this AccountingDocument.
        :type hotel_address_city: str
        """
        if hotel_address_city is None:
            raise ValueError("Invalid value for `hotel_address_city`, must not be `None`")  # noqa: E501

        self._hotel_address_city = hotel_address_city

    @property
    def hotel_address_country_region_code(self) -> str:
        """Gets the hotel_address_country_region_code of this AccountingDocument.


        :return: The hotel_address_country_region_code of this AccountingDocument.
        :rtype: str
        """
        return self._hotel_address_country_region_code

    @hotel_address_country_region_code.setter
    def hotel_address_country_region_code(self, hotel_address_country_region_code: str):
        """Sets the hotel_address_country_region_code of this AccountingDocument.


        :param hotel_address_country_region_code: The hotel_address_country_region_code of this AccountingDocument.
        :type hotel_address_country_region_code: str
        """
        if hotel_address_country_region_code is None:
            raise ValueError("Invalid value for `hotel_address_country_region_code`, must not be `None`")  # noqa: E501

        self._hotel_address_country_region_code = hotel_address_country_region_code

    @property
    def hotel_address_name(self) -> str:
        """Gets the hotel_address_name of this AccountingDocument.


        :return: The hotel_address_name of this AccountingDocument.
        :rtype: str
        """
        return self._hotel_address_name

    @hotel_address_name.setter
    def hotel_address_name(self, hotel_address_name: str):
        """Sets the hotel_address_name of this AccountingDocument.


        :param hotel_address_name: The hotel_address_name of this AccountingDocument.
        :type hotel_address_name: str
        """
        if hotel_address_name is None:
            raise ValueError("Invalid value for `hotel_address_name`, must not be `None`")  # noqa: E501

        self._hotel_address_name = hotel_address_name

    @property
    def hotel_address_name2(self) -> str:
        """Gets the hotel_address_name2 of this AccountingDocument.


        :return: The hotel_address_name2 of this AccountingDocument.
        :rtype: str
        """
        return self._hotel_address_name2

    @hotel_address_name2.setter
    def hotel_address_name2(self, hotel_address_name2: str):
        """Sets the hotel_address_name2 of this AccountingDocument.


        :param hotel_address_name2: The hotel_address_name2 of this AccountingDocument.
        :type hotel_address_name2: str
        """

        self._hotel_address_name2 = hotel_address_name2

    @property
    def hotel_address_post_code(self) -> str:
        """Gets the hotel_address_post_code of this AccountingDocument.


        :return: The hotel_address_post_code of this AccountingDocument.
        :rtype: str
        """
        return self._hotel_address_post_code

    @hotel_address_post_code.setter
    def hotel_address_post_code(self, hotel_address_post_code: str):
        """Sets the hotel_address_post_code of this AccountingDocument.


        :param hotel_address_post_code: The hotel_address_post_code of this AccountingDocument.
        :type hotel_address_post_code: str
        """
        if hotel_address_post_code is None:
            raise ValueError("Invalid value for `hotel_address_post_code`, must not be `None`")  # noqa: E501

        self._hotel_address_post_code = hotel_address_post_code

    @property
    def correction_from_document_no(self) -> str:
        """Gets the correction_from_document_no of this AccountingDocument.


        :return: The correction_from_document_no of this AccountingDocument.
        :rtype: str
        """
        return self._correction_from_document_no

    @correction_from_document_no.setter
    def correction_from_document_no(self, correction_from_document_no: str):
        """Sets the correction_from_document_no of this AccountingDocument.


        :param correction_from_document_no: The correction_from_document_no of this AccountingDocument.
        :type correction_from_document_no: str
        """

        self._correction_from_document_no = correction_from_document_no

    @property
    def document_date(self) -> date:
        """Gets the document_date of this AccountingDocument.


        :return: The document_date of this AccountingDocument.
        :rtype: date
        """
        return self._document_date

    @document_date.setter
    def document_date(self, document_date: date):
        """Sets the document_date of this AccountingDocument.


        :param document_date: The document_date of this AccountingDocument.
        :type document_date: date
        """
        if document_date is None:
            raise ValueError("Invalid value for `document_date`, must not be `None`")  # noqa: E501

        self._document_date = document_date

    @property
    def external_document_no(self) -> str:
        """Gets the external_document_no of this AccountingDocument.


        :return: The external_document_no of this AccountingDocument.
        :rtype: str
        """
        return self._external_document_no

    @external_document_no.setter
    def external_document_no(self, external_document_no: str):
        """Sets the external_document_no of this AccountingDocument.


        :param external_document_no: The external_document_no of this AccountingDocument.
        :type external_document_no: str
        """

        self._external_document_no = external_document_no

    @property
    def has_pdf(self) -> bool:
        """Gets the has_pdf of this AccountingDocument.


        :return: The has_pdf of this AccountingDocument.
        :rtype: bool
        """
        return self._has_pdf

    @has_pdf.setter
    def has_pdf(self, has_pdf: bool):
        """Sets the has_pdf of this AccountingDocument.


        :param has_pdf: The has_pdf of this AccountingDocument.
        :type has_pdf: bool
        """
        if has_pdf is None:
            raise ValueError("Invalid value for `has_pdf`, must not be `None`")  # noqa: E501

        self._has_pdf = has_pdf

    @property
    def positions(self) -> List[Position]:
        """Gets the positions of this AccountingDocument.


        :return: The positions of this AccountingDocument.
        :rtype: List[Position]
        """
        return self._positions

    @positions.setter
    def positions(self, positions: List[Position]):
        """Sets the positions of this AccountingDocument.


        :param positions: The positions of this AccountingDocument.
        :type positions: List[Position]
        """

        self._positions = positions
