# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oip_api_server.models.base_model_ import Model
from oip_api_server import util


class HotelsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, vat_registration_number: str=None, no_corrections: str=None, invoice_address_no: str=None, hotel_address_no: str=None, company_no: str=None, invoice_address_name: str=None, invoice_address_name2: str=None, invoice_address_line1: str=None, invoice_address_line2: str=None, primary_contact_no: str=None, brand_no: str=None, brand_name: str=None, invoice_address_city: str=None, contract_status: str=None, contract_status_name: str=None, chain_no: str=None, chain_name: str=None, invoice_address_country_region_code: str=None, hotel_status: str=None, invoice_address_email: str=None, invoice_address_email_copy: str=None, invoice_address_fax_no: str=None, invoice_address_fax_no_copy: str=None, invoice_address_language_code: str=None, reason_code: str=None, no_sepa_core: str=None, reason_name: str=None, reason_date: str=None, phone_no: str=None, hrs_contact: str=None, invoioce_address_zip: str=None, ccpkn: str=None, cc_name: str=None, cc_valid_to: str=None, contact_person_first_name: str=None, contact_person_middle_name: str=None, contact_person_last_name: str=None, contact_person_email: str=None, contact_person_phone: str=None, contact_person_fax: str=None, hotel_address_name: str=None, hotel_address_country_region_code: str=None, hotel_address_language_code: str=None, hotel_address_name2: str=None, hotel_address_line1: str=None, hotel_address_line2: str=None, hotel_address_city: str=None, hotel_address_zip: str=None, hotel_address_phone_no: str=None, hotel_address_fax_no: str=None, hotel_address_email: str=None, web_portal_enabled: bool=None, correspondence_type: str=None, accounting_contact: str=None, deduction_type: str=None, tenant: str=None):  # noqa: E501
        """HotelsBody - a model defined in Swagger

        :param vat_registration_number: The vat_registration_number of this HotelsBody.  # noqa: E501
        :type vat_registration_number: str
        :param no_corrections: The no_corrections of this HotelsBody.  # noqa: E501
        :type no_corrections: str
        :param invoice_address_no: The invoice_address_no of this HotelsBody.  # noqa: E501
        :type invoice_address_no: str
        :param hotel_address_no: The hotel_address_no of this HotelsBody.  # noqa: E501
        :type hotel_address_no: str
        :param company_no: The company_no of this HotelsBody.  # noqa: E501
        :type company_no: str
        :param invoice_address_name: The invoice_address_name of this HotelsBody.  # noqa: E501
        :type invoice_address_name: str
        :param invoice_address_name2: The invoice_address_name2 of this HotelsBody.  # noqa: E501
        :type invoice_address_name2: str
        :param invoice_address_line1: The invoice_address_line1 of this HotelsBody.  # noqa: E501
        :type invoice_address_line1: str
        :param invoice_address_line2: The invoice_address_line2 of this HotelsBody.  # noqa: E501
        :type invoice_address_line2: str
        :param primary_contact_no: The primary_contact_no of this HotelsBody.  # noqa: E501
        :type primary_contact_no: str
        :param brand_no: The brand_no of this HotelsBody.  # noqa: E501
        :type brand_no: str
        :param brand_name: The brand_name of this HotelsBody.  # noqa: E501
        :type brand_name: str
        :param invoice_address_city: The invoice_address_city of this HotelsBody.  # noqa: E501
        :type invoice_address_city: str
        :param contract_status: The contract_status of this HotelsBody.  # noqa: E501
        :type contract_status: str
        :param contract_status_name: The contract_status_name of this HotelsBody.  # noqa: E501
        :type contract_status_name: str
        :param chain_no: The chain_no of this HotelsBody.  # noqa: E501
        :type chain_no: str
        :param chain_name: The chain_name of this HotelsBody.  # noqa: E501
        :type chain_name: str
        :param invoice_address_country_region_code: The invoice_address_country_region_code of this HotelsBody.  # noqa: E501
        :type invoice_address_country_region_code: str
        :param hotel_status: The hotel_status of this HotelsBody.  # noqa: E501
        :type hotel_status: str
        :param invoice_address_email: The invoice_address_email of this HotelsBody.  # noqa: E501
        :type invoice_address_email: str
        :param invoice_address_email_copy: The invoice_address_email_copy of this HotelsBody.  # noqa: E501
        :type invoice_address_email_copy: str
        :param invoice_address_fax_no: The invoice_address_fax_no of this HotelsBody.  # noqa: E501
        :type invoice_address_fax_no: str
        :param invoice_address_fax_no_copy: The invoice_address_fax_no_copy of this HotelsBody.  # noqa: E501
        :type invoice_address_fax_no_copy: str
        :param invoice_address_language_code: The invoice_address_language_code of this HotelsBody.  # noqa: E501
        :type invoice_address_language_code: str
        :param reason_code: The reason_code of this HotelsBody.  # noqa: E501
        :type reason_code: str
        :param no_sepa_core: The no_sepa_core of this HotelsBody.  # noqa: E501
        :type no_sepa_core: str
        :param reason_name: The reason_name of this HotelsBody.  # noqa: E501
        :type reason_name: str
        :param reason_date: The reason_date of this HotelsBody.  # noqa: E501
        :type reason_date: str
        :param phone_no: The phone_no of this HotelsBody.  # noqa: E501
        :type phone_no: str
        :param hrs_contact: The hrs_contact of this HotelsBody.  # noqa: E501
        :type hrs_contact: str
        :param invoioce_address_zip: The invoioce_address_zip of this HotelsBody.  # noqa: E501
        :type invoioce_address_zip: str
        :param ccpkn: The ccpkn of this HotelsBody.  # noqa: E501
        :type ccpkn: str
        :param cc_name: The cc_name of this HotelsBody.  # noqa: E501
        :type cc_name: str
        :param cc_valid_to: The cc_valid_to of this HotelsBody.  # noqa: E501
        :type cc_valid_to: str
        :param contact_person_first_name: The contact_person_first_name of this HotelsBody.  # noqa: E501
        :type contact_person_first_name: str
        :param contact_person_middle_name: The contact_person_middle_name of this HotelsBody.  # noqa: E501
        :type contact_person_middle_name: str
        :param contact_person_last_name: The contact_person_last_name of this HotelsBody.  # noqa: E501
        :type contact_person_last_name: str
        :param contact_person_email: The contact_person_email of this HotelsBody.  # noqa: E501
        :type contact_person_email: str
        :param contact_person_phone: The contact_person_phone of this HotelsBody.  # noqa: E501
        :type contact_person_phone: str
        :param contact_person_fax: The contact_person_fax of this HotelsBody.  # noqa: E501
        :type contact_person_fax: str
        :param hotel_address_name: The hotel_address_name of this HotelsBody.  # noqa: E501
        :type hotel_address_name: str
        :param hotel_address_country_region_code: The hotel_address_country_region_code of this HotelsBody.  # noqa: E501
        :type hotel_address_country_region_code: str
        :param hotel_address_language_code: The hotel_address_language_code of this HotelsBody.  # noqa: E501
        :type hotel_address_language_code: str
        :param hotel_address_name2: The hotel_address_name2 of this HotelsBody.  # noqa: E501
        :type hotel_address_name2: str
        :param hotel_address_line1: The hotel_address_line1 of this HotelsBody.  # noqa: E501
        :type hotel_address_line1: str
        :param hotel_address_line2: The hotel_address_line2 of this HotelsBody.  # noqa: E501
        :type hotel_address_line2: str
        :param hotel_address_city: The hotel_address_city of this HotelsBody.  # noqa: E501
        :type hotel_address_city: str
        :param hotel_address_zip: The hotel_address_zip of this HotelsBody.  # noqa: E501
        :type hotel_address_zip: str
        :param hotel_address_phone_no: The hotel_address_phone_no of this HotelsBody.  # noqa: E501
        :type hotel_address_phone_no: str
        :param hotel_address_fax_no: The hotel_address_fax_no of this HotelsBody.  # noqa: E501
        :type hotel_address_fax_no: str
        :param hotel_address_email: The hotel_address_email of this HotelsBody.  # noqa: E501
        :type hotel_address_email: str
        :param web_portal_enabled: The web_portal_enabled of this HotelsBody.  # noqa: E501
        :type web_portal_enabled: bool
        :param correspondence_type: The correspondence_type of this HotelsBody.  # noqa: E501
        :type correspondence_type: str
        :param accounting_contact: The accounting_contact of this HotelsBody.  # noqa: E501
        :type accounting_contact: str
        :param deduction_type: The deduction_type of this HotelsBody.  # noqa: E501
        :type deduction_type: str
        :param tenant: The tenant of this HotelsBody.  # noqa: E501
        :type tenant: str
        """
        self.swagger_types = {
            'vat_registration_number': str,
            'no_corrections': str,
            'invoice_address_no': str,
            'hotel_address_no': str,
            'company_no': str,
            'invoice_address_name': str,
            'invoice_address_name2': str,
            'invoice_address_line1': str,
            'invoice_address_line2': str,
            'primary_contact_no': str,
            'brand_no': str,
            'brand_name': str,
            'invoice_address_city': str,
            'contract_status': str,
            'contract_status_name': str,
            'chain_no': str,
            'chain_name': str,
            'invoice_address_country_region_code': str,
            'hotel_status': str,
            'invoice_address_email': str,
            'invoice_address_email_copy': str,
            'invoice_address_fax_no': str,
            'invoice_address_fax_no_copy': str,
            'invoice_address_language_code': str,
            'reason_code': str,
            'no_sepa_core': str,
            'reason_name': str,
            'reason_date': str,
            'phone_no': str,
            'hrs_contact': str,
            'invoioce_address_zip': str,
            'ccpkn': str,
            'cc_name': str,
            'cc_valid_to': str,
            'contact_person_first_name': str,
            'contact_person_middle_name': str,
            'contact_person_last_name': str,
            'contact_person_email': str,
            'contact_person_phone': str,
            'contact_person_fax': str,
            'hotel_address_name': str,
            'hotel_address_country_region_code': str,
            'hotel_address_language_code': str,
            'hotel_address_name2': str,
            'hotel_address_line1': str,
            'hotel_address_line2': str,
            'hotel_address_city': str,
            'hotel_address_zip': str,
            'hotel_address_phone_no': str,
            'hotel_address_fax_no': str,
            'hotel_address_email': str,
            'web_portal_enabled': bool,
            'correspondence_type': str,
            'accounting_contact': str,
            'deduction_type': str,
            'tenant': str
        }

        self.attribute_map = {
            'vat_registration_number': 'VATRegistrationNumber',
            'no_corrections': 'NoCorrections',
            'invoice_address_no': 'InvoiceAddressNo',
            'hotel_address_no': 'HotelAddressNo',
            'company_no': 'CompanyNo',
            'invoice_address_name': 'InvoiceAddressName',
            'invoice_address_name2': 'InvoiceAddressName2',
            'invoice_address_line1': 'InvoiceAddressLine1',
            'invoice_address_line2': 'InvoiceAddressLine2',
            'primary_contact_no': 'PrimaryContactNo',
            'brand_no': 'BrandNo',
            'brand_name': 'BrandName',
            'invoice_address_city': 'InvoiceAddressCity',
            'contract_status': 'ContractStatus',
            'contract_status_name': 'ContractStatusName',
            'chain_no': 'ChainNo',
            'chain_name': 'ChainName',
            'invoice_address_country_region_code': 'InvoiceAddressCountryRegionCode',
            'hotel_status': 'HotelStatus',
            'invoice_address_email': 'InvoiceAddressEmail',
            'invoice_address_email_copy': 'InvoiceAddressEmailCopy',
            'invoice_address_fax_no': 'InvoiceAddressFaxNo',
            'invoice_address_fax_no_copy': 'InvoiceAddressFaxNoCopy',
            'invoice_address_language_code': 'InvoiceAddressLanguageCode',
            'reason_code': 'ReasonCode',
            'no_sepa_core': 'NoSepaCore',
            'reason_name': 'ReasonName',
            'reason_date': 'ReasonDate',
            'phone_no': 'PhoneNo',
            'hrs_contact': 'HRSContact',
            'invoioce_address_zip': 'InvoioceAddressZip',
            'ccpkn': 'CCPKN',
            'cc_name': 'CCName',
            'cc_valid_to': 'CCValidTo',
            'contact_person_first_name': 'ContactPersonFirstName',
            'contact_person_middle_name': 'ContactPersonMiddleName',
            'contact_person_last_name': 'ContactPersonLastName',
            'contact_person_email': 'ContactPersonEmail',
            'contact_person_phone': 'ContactPersonPhone',
            'contact_person_fax': 'ContactPersonFax',
            'hotel_address_name': 'HotelAddressName',
            'hotel_address_country_region_code': 'HotelAddressCountryRegionCode',
            'hotel_address_language_code': 'HotelAddressLanguageCode',
            'hotel_address_name2': 'HotelAddressName2',
            'hotel_address_line1': 'HotelAddressLine1',
            'hotel_address_line2': 'HotelAddressLine2',
            'hotel_address_city': 'HotelAddressCity',
            'hotel_address_zip': 'HotelAddressZip',
            'hotel_address_phone_no': 'HotelAddressPhoneNo',
            'hotel_address_fax_no': 'HotelAddressFaxNo',
            'hotel_address_email': 'HotelAddressEmail',
            'web_portal_enabled': 'WebPortalEnabled',
            'correspondence_type': 'CorrespondenceType',
            'accounting_contact': 'AccountingContact',
            'deduction_type': 'DeductionType',
            'tenant': 'Tenant'
        }
        self._vat_registration_number = vat_registration_number
        self._no_corrections = no_corrections
        self._invoice_address_no = invoice_address_no
        self._hotel_address_no = hotel_address_no
        self._company_no = company_no
        self._invoice_address_name = invoice_address_name
        self._invoice_address_name2 = invoice_address_name2
        self._invoice_address_line1 = invoice_address_line1
        self._invoice_address_line2 = invoice_address_line2
        self._primary_contact_no = primary_contact_no
        self._brand_no = brand_no
        self._brand_name = brand_name
        self._invoice_address_city = invoice_address_city
        self._contract_status = contract_status
        self._contract_status_name = contract_status_name
        self._chain_no = chain_no
        self._chain_name = chain_name
        self._invoice_address_country_region_code = invoice_address_country_region_code
        self._hotel_status = hotel_status
        self._invoice_address_email = invoice_address_email
        self._invoice_address_email_copy = invoice_address_email_copy
        self._invoice_address_fax_no = invoice_address_fax_no
        self._invoice_address_fax_no_copy = invoice_address_fax_no_copy
        self._invoice_address_language_code = invoice_address_language_code
        self._reason_code = reason_code
        self._no_sepa_core = no_sepa_core
        self._reason_name = reason_name
        self._reason_date = reason_date
        self._phone_no = phone_no
        self._hrs_contact = hrs_contact
        self._invoioce_address_zip = invoioce_address_zip
        self._ccpkn = ccpkn
        self._cc_name = cc_name
        self._cc_valid_to = cc_valid_to
        self._contact_person_first_name = contact_person_first_name
        self._contact_person_middle_name = contact_person_middle_name
        self._contact_person_last_name = contact_person_last_name
        self._contact_person_email = contact_person_email
        self._contact_person_phone = contact_person_phone
        self._contact_person_fax = contact_person_fax
        self._hotel_address_name = hotel_address_name
        self._hotel_address_country_region_code = hotel_address_country_region_code
        self._hotel_address_language_code = hotel_address_language_code
        self._hotel_address_name2 = hotel_address_name2
        self._hotel_address_line1 = hotel_address_line1
        self._hotel_address_line2 = hotel_address_line2
        self._hotel_address_city = hotel_address_city
        self._hotel_address_zip = hotel_address_zip
        self._hotel_address_phone_no = hotel_address_phone_no
        self._hotel_address_fax_no = hotel_address_fax_no
        self._hotel_address_email = hotel_address_email
        self._web_portal_enabled = web_portal_enabled
        self._correspondence_type = correspondence_type
        self._accounting_contact = accounting_contact
        self._deduction_type = deduction_type
        self._tenant = tenant

    @classmethod
    def from_dict(cls, dikt) -> 'HotelsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The hotels_body of this HotelsBody.  # noqa: E501
        :rtype: HotelsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vat_registration_number(self) -> str:
        """Gets the vat_registration_number of this HotelsBody.

        The VAT registration number of the hotel  # noqa: E501

        :return: The vat_registration_number of this HotelsBody.
        :rtype: str
        """
        return self._vat_registration_number

    @vat_registration_number.setter
    def vat_registration_number(self, vat_registration_number: str):
        """Sets the vat_registration_number of this HotelsBody.

        The VAT registration number of the hotel  # noqa: E501

        :param vat_registration_number: The vat_registration_number of this HotelsBody.
        :type vat_registration_number: str
        """

        self._vat_registration_number = vat_registration_number

    @property
    def no_corrections(self) -> str:
        """Gets the no_corrections of this HotelsBody.

        Indicates if there are no corrections  # noqa: E501

        :return: The no_corrections of this HotelsBody.
        :rtype: str
        """
        return self._no_corrections

    @no_corrections.setter
    def no_corrections(self, no_corrections: str):
        """Sets the no_corrections of this HotelsBody.

        Indicates if there are no corrections  # noqa: E501

        :param no_corrections: The no_corrections of this HotelsBody.
        :type no_corrections: str
        """

        self._no_corrections = no_corrections

    @property
    def invoice_address_no(self) -> str:
        """Gets the invoice_address_no of this HotelsBody.

        The invoice address number  # noqa: E501

        :return: The invoice_address_no of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_no

    @invoice_address_no.setter
    def invoice_address_no(self, invoice_address_no: str):
        """Sets the invoice_address_no of this HotelsBody.

        The invoice address number  # noqa: E501

        :param invoice_address_no: The invoice_address_no of this HotelsBody.
        :type invoice_address_no: str
        """

        self._invoice_address_no = invoice_address_no

    @property
    def hotel_address_no(self) -> str:
        """Gets the hotel_address_no of this HotelsBody.

        The hotel address number  # noqa: E501

        :return: The hotel_address_no of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_no

    @hotel_address_no.setter
    def hotel_address_no(self, hotel_address_no: str):
        """Sets the hotel_address_no of this HotelsBody.

        The hotel address number  # noqa: E501

        :param hotel_address_no: The hotel_address_no of this HotelsBody.
        :type hotel_address_no: str
        """

        self._hotel_address_no = hotel_address_no

    @property
    def company_no(self) -> str:
        """Gets the company_no of this HotelsBody.

        The company number of the hotel  # noqa: E501

        :return: The company_no of this HotelsBody.
        :rtype: str
        """
        return self._company_no

    @company_no.setter
    def company_no(self, company_no: str):
        """Sets the company_no of this HotelsBody.

        The company number of the hotel  # noqa: E501

        :param company_no: The company_no of this HotelsBody.
        :type company_no: str
        """

        self._company_no = company_no

    @property
    def invoice_address_name(self) -> str:
        """Gets the invoice_address_name of this HotelsBody.

        The name of the invoice address  # noqa: E501

        :return: The invoice_address_name of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_name

    @invoice_address_name.setter
    def invoice_address_name(self, invoice_address_name: str):
        """Sets the invoice_address_name of this HotelsBody.

        The name of the invoice address  # noqa: E501

        :param invoice_address_name: The invoice_address_name of this HotelsBody.
        :type invoice_address_name: str
        """

        self._invoice_address_name = invoice_address_name

    @property
    def invoice_address_name2(self) -> str:
        """Gets the invoice_address_name2 of this HotelsBody.

        The second line of the invoice address name  # noqa: E501

        :return: The invoice_address_name2 of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_name2

    @invoice_address_name2.setter
    def invoice_address_name2(self, invoice_address_name2: str):
        """Sets the invoice_address_name2 of this HotelsBody.

        The second line of the invoice address name  # noqa: E501

        :param invoice_address_name2: The invoice_address_name2 of this HotelsBody.
        :type invoice_address_name2: str
        """

        self._invoice_address_name2 = invoice_address_name2

    @property
    def invoice_address_line1(self) -> str:
        """Gets the invoice_address_line1 of this HotelsBody.

        The first line of the invoice address  # noqa: E501

        :return: The invoice_address_line1 of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_line1

    @invoice_address_line1.setter
    def invoice_address_line1(self, invoice_address_line1: str):
        """Sets the invoice_address_line1 of this HotelsBody.

        The first line of the invoice address  # noqa: E501

        :param invoice_address_line1: The invoice_address_line1 of this HotelsBody.
        :type invoice_address_line1: str
        """

        self._invoice_address_line1 = invoice_address_line1

    @property
    def invoice_address_line2(self) -> str:
        """Gets the invoice_address_line2 of this HotelsBody.

        The second line of the invoice address  # noqa: E501

        :return: The invoice_address_line2 of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_line2

    @invoice_address_line2.setter
    def invoice_address_line2(self, invoice_address_line2: str):
        """Sets the invoice_address_line2 of this HotelsBody.

        The second line of the invoice address  # noqa: E501

        :param invoice_address_line2: The invoice_address_line2 of this HotelsBody.
        :type invoice_address_line2: str
        """

        self._invoice_address_line2 = invoice_address_line2

    @property
    def primary_contact_no(self) -> str:
        """Gets the primary_contact_no of this HotelsBody.

        The primary contact number  # noqa: E501

        :return: The primary_contact_no of this HotelsBody.
        :rtype: str
        """
        return self._primary_contact_no

    @primary_contact_no.setter
    def primary_contact_no(self, primary_contact_no: str):
        """Sets the primary_contact_no of this HotelsBody.

        The primary contact number  # noqa: E501

        :param primary_contact_no: The primary_contact_no of this HotelsBody.
        :type primary_contact_no: str
        """

        self._primary_contact_no = primary_contact_no

    @property
    def brand_no(self) -> str:
        """Gets the brand_no of this HotelsBody.

        The brand number  # noqa: E501

        :return: The brand_no of this HotelsBody.
        :rtype: str
        """
        return self._brand_no

    @brand_no.setter
    def brand_no(self, brand_no: str):
        """Sets the brand_no of this HotelsBody.

        The brand number  # noqa: E501

        :param brand_no: The brand_no of this HotelsBody.
        :type brand_no: str
        """

        self._brand_no = brand_no

    @property
    def brand_name(self) -> str:
        """Gets the brand_name of this HotelsBody.

        The brand name  # noqa: E501

        :return: The brand_name of this HotelsBody.
        :rtype: str
        """
        return self._brand_name

    @brand_name.setter
    def brand_name(self, brand_name: str):
        """Sets the brand_name of this HotelsBody.

        The brand name  # noqa: E501

        :param brand_name: The brand_name of this HotelsBody.
        :type brand_name: str
        """

        self._brand_name = brand_name

    @property
    def invoice_address_city(self) -> str:
        """Gets the invoice_address_city of this HotelsBody.

        The city of the invoice address  # noqa: E501

        :return: The invoice_address_city of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_city

    @invoice_address_city.setter
    def invoice_address_city(self, invoice_address_city: str):
        """Sets the invoice_address_city of this HotelsBody.

        The city of the invoice address  # noqa: E501

        :param invoice_address_city: The invoice_address_city of this HotelsBody.
        :type invoice_address_city: str
        """

        self._invoice_address_city = invoice_address_city

    @property
    def contract_status(self) -> str:
        """Gets the contract_status of this HotelsBody.

        The contract status  # noqa: E501

        :return: The contract_status of this HotelsBody.
        :rtype: str
        """
        return self._contract_status

    @contract_status.setter
    def contract_status(self, contract_status: str):
        """Sets the contract_status of this HotelsBody.

        The contract status  # noqa: E501

        :param contract_status: The contract_status of this HotelsBody.
        :type contract_status: str
        """

        self._contract_status = contract_status

    @property
    def contract_status_name(self) -> str:
        """Gets the contract_status_name of this HotelsBody.

        The name of the contract status  # noqa: E501

        :return: The contract_status_name of this HotelsBody.
        :rtype: str
        """
        return self._contract_status_name

    @contract_status_name.setter
    def contract_status_name(self, contract_status_name: str):
        """Sets the contract_status_name of this HotelsBody.

        The name of the contract status  # noqa: E501

        :param contract_status_name: The contract_status_name of this HotelsBody.
        :type contract_status_name: str
        """

        self._contract_status_name = contract_status_name

    @property
    def chain_no(self) -> str:
        """Gets the chain_no of this HotelsBody.

        The chain number  # noqa: E501

        :return: The chain_no of this HotelsBody.
        :rtype: str
        """
        return self._chain_no

    @chain_no.setter
    def chain_no(self, chain_no: str):
        """Sets the chain_no of this HotelsBody.

        The chain number  # noqa: E501

        :param chain_no: The chain_no of this HotelsBody.
        :type chain_no: str
        """

        self._chain_no = chain_no

    @property
    def chain_name(self) -> str:
        """Gets the chain_name of this HotelsBody.

        The name of the chain  # noqa: E501

        :return: The chain_name of this HotelsBody.
        :rtype: str
        """
        return self._chain_name

    @chain_name.setter
    def chain_name(self, chain_name: str):
        """Sets the chain_name of this HotelsBody.

        The name of the chain  # noqa: E501

        :param chain_name: The chain_name of this HotelsBody.
        :type chain_name: str
        """

        self._chain_name = chain_name

    @property
    def invoice_address_country_region_code(self) -> str:
        """Gets the invoice_address_country_region_code of this HotelsBody.

        The country/region code of the invoice address  # noqa: E501

        :return: The invoice_address_country_region_code of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_country_region_code

    @invoice_address_country_region_code.setter
    def invoice_address_country_region_code(self, invoice_address_country_region_code: str):
        """Sets the invoice_address_country_region_code of this HotelsBody.

        The country/region code of the invoice address  # noqa: E501

        :param invoice_address_country_region_code: The invoice_address_country_region_code of this HotelsBody.
        :type invoice_address_country_region_code: str
        """

        self._invoice_address_country_region_code = invoice_address_country_region_code

    @property
    def hotel_status(self) -> str:
        """Gets the hotel_status of this HotelsBody.

        The hotel status  # noqa: E501

        :return: The hotel_status of this HotelsBody.
        :rtype: str
        """
        return self._hotel_status

    @hotel_status.setter
    def hotel_status(self, hotel_status: str):
        """Sets the hotel_status of this HotelsBody.

        The hotel status  # noqa: E501

        :param hotel_status: The hotel_status of this HotelsBody.
        :type hotel_status: str
        """

        self._hotel_status = hotel_status

    @property
    def invoice_address_email(self) -> str:
        """Gets the invoice_address_email of this HotelsBody.

        The email address of the invoice address  # noqa: E501

        :return: The invoice_address_email of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_email

    @invoice_address_email.setter
    def invoice_address_email(self, invoice_address_email: str):
        """Sets the invoice_address_email of this HotelsBody.

        The email address of the invoice address  # noqa: E501

        :param invoice_address_email: The invoice_address_email of this HotelsBody.
        :type invoice_address_email: str
        """

        self._invoice_address_email = invoice_address_email

    @property
    def invoice_address_email_copy(self) -> str:
        """Gets the invoice_address_email_copy of this HotelsBody.

        The copy email address of the invoice address  # noqa: E501

        :return: The invoice_address_email_copy of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_email_copy

    @invoice_address_email_copy.setter
    def invoice_address_email_copy(self, invoice_address_email_copy: str):
        """Sets the invoice_address_email_copy of this HotelsBody.

        The copy email address of the invoice address  # noqa: E501

        :param invoice_address_email_copy: The invoice_address_email_copy of this HotelsBody.
        :type invoice_address_email_copy: str
        """

        self._invoice_address_email_copy = invoice_address_email_copy

    @property
    def invoice_address_fax_no(self) -> str:
        """Gets the invoice_address_fax_no of this HotelsBody.

        The fax number of the invoice address  # noqa: E501

        :return: The invoice_address_fax_no of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_fax_no

    @invoice_address_fax_no.setter
    def invoice_address_fax_no(self, invoice_address_fax_no: str):
        """Sets the invoice_address_fax_no of this HotelsBody.

        The fax number of the invoice address  # noqa: E501

        :param invoice_address_fax_no: The invoice_address_fax_no of this HotelsBody.
        :type invoice_address_fax_no: str
        """

        self._invoice_address_fax_no = invoice_address_fax_no

    @property
    def invoice_address_fax_no_copy(self) -> str:
        """Gets the invoice_address_fax_no_copy of this HotelsBody.

        The copy fax number of the invoice address  # noqa: E501

        :return: The invoice_address_fax_no_copy of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_fax_no_copy

    @invoice_address_fax_no_copy.setter
    def invoice_address_fax_no_copy(self, invoice_address_fax_no_copy: str):
        """Sets the invoice_address_fax_no_copy of this HotelsBody.

        The copy fax number of the invoice address  # noqa: E501

        :param invoice_address_fax_no_copy: The invoice_address_fax_no_copy of this HotelsBody.
        :type invoice_address_fax_no_copy: str
        """

        self._invoice_address_fax_no_copy = invoice_address_fax_no_copy

    @property
    def invoice_address_language_code(self) -> str:
        """Gets the invoice_address_language_code of this HotelsBody.

        The language code of the invoice address  # noqa: E501

        :return: The invoice_address_language_code of this HotelsBody.
        :rtype: str
        """
        return self._invoice_address_language_code

    @invoice_address_language_code.setter
    def invoice_address_language_code(self, invoice_address_language_code: str):
        """Sets the invoice_address_language_code of this HotelsBody.

        The language code of the invoice address  # noqa: E501

        :param invoice_address_language_code: The invoice_address_language_code of this HotelsBody.
        :type invoice_address_language_code: str
        """

        self._invoice_address_language_code = invoice_address_language_code

    @property
    def reason_code(self) -> str:
        """Gets the reason_code of this HotelsBody.

        The reason code  # noqa: E501

        :return: The reason_code of this HotelsBody.
        :rtype: str
        """
        return self._reason_code

    @reason_code.setter
    def reason_code(self, reason_code: str):
        """Sets the reason_code of this HotelsBody.

        The reason code  # noqa: E501

        :param reason_code: The reason_code of this HotelsBody.
        :type reason_code: str
        """

        self._reason_code = reason_code

    @property
    def no_sepa_core(self) -> str:
        """Gets the no_sepa_core of this HotelsBody.

        Indicates if SEPA_CORE is enabled or not  # noqa: E501

        :return: The no_sepa_core of this HotelsBody.
        :rtype: str
        """
        return self._no_sepa_core

    @no_sepa_core.setter
    def no_sepa_core(self, no_sepa_core: str):
        """Sets the no_sepa_core of this HotelsBody.

        Indicates if SEPA_CORE is enabled or not  # noqa: E501

        :param no_sepa_core: The no_sepa_core of this HotelsBody.
        :type no_sepa_core: str
        """

        self._no_sepa_core = no_sepa_core

    @property
    def reason_name(self) -> str:
        """Gets the reason_name of this HotelsBody.

        The name of the reason  # noqa: E501

        :return: The reason_name of this HotelsBody.
        :rtype: str
        """
        return self._reason_name

    @reason_name.setter
    def reason_name(self, reason_name: str):
        """Sets the reason_name of this HotelsBody.

        The name of the reason  # noqa: E501

        :param reason_name: The reason_name of this HotelsBody.
        :type reason_name: str
        """

        self._reason_name = reason_name

    @property
    def reason_date(self) -> str:
        """Gets the reason_date of this HotelsBody.

        The date of the reason  # noqa: E501

        :return: The reason_date of this HotelsBody.
        :rtype: str
        """
        return self._reason_date

    @reason_date.setter
    def reason_date(self, reason_date: str):
        """Sets the reason_date of this HotelsBody.

        The date of the reason  # noqa: E501

        :param reason_date: The reason_date of this HotelsBody.
        :type reason_date: str
        """

        self._reason_date = reason_date

    @property
    def phone_no(self) -> str:
        """Gets the phone_no of this HotelsBody.

        The phone number of the invoice address  # noqa: E501

        :return: The phone_no of this HotelsBody.
        :rtype: str
        """
        return self._phone_no

    @phone_no.setter
    def phone_no(self, phone_no: str):
        """Sets the phone_no of this HotelsBody.

        The phone number of the invoice address  # noqa: E501

        :param phone_no: The phone_no of this HotelsBody.
        :type phone_no: str
        """

        self._phone_no = phone_no

    @property
    def hrs_contact(self) -> str:
        """Gets the hrs_contact of this HotelsBody.

        The HRS contact code  # noqa: E501

        :return: The hrs_contact of this HotelsBody.
        :rtype: str
        """
        return self._hrs_contact

    @hrs_contact.setter
    def hrs_contact(self, hrs_contact: str):
        """Sets the hrs_contact of this HotelsBody.

        The HRS contact code  # noqa: E501

        :param hrs_contact: The hrs_contact of this HotelsBody.
        :type hrs_contact: str
        """

        self._hrs_contact = hrs_contact

    @property
    def invoioce_address_zip(self) -> str:
        """Gets the invoioce_address_zip of this HotelsBody.

        The zip code of the invoice address  # noqa: E501

        :return: The invoioce_address_zip of this HotelsBody.
        :rtype: str
        """
        return self._invoioce_address_zip

    @invoioce_address_zip.setter
    def invoioce_address_zip(self, invoioce_address_zip: str):
        """Sets the invoioce_address_zip of this HotelsBody.

        The zip code of the invoice address  # noqa: E501

        :param invoioce_address_zip: The invoioce_address_zip of this HotelsBody.
        :type invoioce_address_zip: str
        """

        self._invoioce_address_zip = invoioce_address_zip

    @property
    def ccpkn(self) -> str:
        """Gets the ccpkn of this HotelsBody.

        The CC PKN  # noqa: E501

        :return: The ccpkn of this HotelsBody.
        :rtype: str
        """
        return self._ccpkn

    @ccpkn.setter
    def ccpkn(self, ccpkn: str):
        """Sets the ccpkn of this HotelsBody.

        The CC PKN  # noqa: E501

        :param ccpkn: The ccpkn of this HotelsBody.
        :type ccpkn: str
        """

        self._ccpkn = ccpkn

    @property
    def cc_name(self) -> str:
        """Gets the cc_name of this HotelsBody.

        The name of the credit card  # noqa: E501

        :return: The cc_name of this HotelsBody.
        :rtype: str
        """
        return self._cc_name

    @cc_name.setter
    def cc_name(self, cc_name: str):
        """Sets the cc_name of this HotelsBody.

        The name of the credit card  # noqa: E501

        :param cc_name: The cc_name of this HotelsBody.
        :type cc_name: str
        """

        self._cc_name = cc_name

    @property
    def cc_valid_to(self) -> str:
        """Gets the cc_valid_to of this HotelsBody.

        The valid-to date of the credit card  # noqa: E501

        :return: The cc_valid_to of this HotelsBody.
        :rtype: str
        """
        return self._cc_valid_to

    @cc_valid_to.setter
    def cc_valid_to(self, cc_valid_to: str):
        """Sets the cc_valid_to of this HotelsBody.

        The valid-to date of the credit card  # noqa: E501

        :param cc_valid_to: The cc_valid_to of this HotelsBody.
        :type cc_valid_to: str
        """

        self._cc_valid_to = cc_valid_to

    @property
    def contact_person_first_name(self) -> str:
        """Gets the contact_person_first_name of this HotelsBody.

        The first name of the contact person  # noqa: E501

        :return: The contact_person_first_name of this HotelsBody.
        :rtype: str
        """
        return self._contact_person_first_name

    @contact_person_first_name.setter
    def contact_person_first_name(self, contact_person_first_name: str):
        """Sets the contact_person_first_name of this HotelsBody.

        The first name of the contact person  # noqa: E501

        :param contact_person_first_name: The contact_person_first_name of this HotelsBody.
        :type contact_person_first_name: str
        """

        self._contact_person_first_name = contact_person_first_name

    @property
    def contact_person_middle_name(self) -> str:
        """Gets the contact_person_middle_name of this HotelsBody.

        The middle name of the contact person  # noqa: E501

        :return: The contact_person_middle_name of this HotelsBody.
        :rtype: str
        """
        return self._contact_person_middle_name

    @contact_person_middle_name.setter
    def contact_person_middle_name(self, contact_person_middle_name: str):
        """Sets the contact_person_middle_name of this HotelsBody.

        The middle name of the contact person  # noqa: E501

        :param contact_person_middle_name: The contact_person_middle_name of this HotelsBody.
        :type contact_person_middle_name: str
        """

        self._contact_person_middle_name = contact_person_middle_name

    @property
    def contact_person_last_name(self) -> str:
        """Gets the contact_person_last_name of this HotelsBody.

        The last name of the contact person  # noqa: E501

        :return: The contact_person_last_name of this HotelsBody.
        :rtype: str
        """
        return self._contact_person_last_name

    @contact_person_last_name.setter
    def contact_person_last_name(self, contact_person_last_name: str):
        """Sets the contact_person_last_name of this HotelsBody.

        The last name of the contact person  # noqa: E501

        :param contact_person_last_name: The contact_person_last_name of this HotelsBody.
        :type contact_person_last_name: str
        """

        self._contact_person_last_name = contact_person_last_name

    @property
    def contact_person_email(self) -> str:
        """Gets the contact_person_email of this HotelsBody.

        The email address of the contact person  # noqa: E501

        :return: The contact_person_email of this HotelsBody.
        :rtype: str
        """
        return self._contact_person_email

    @contact_person_email.setter
    def contact_person_email(self, contact_person_email: str):
        """Sets the contact_person_email of this HotelsBody.

        The email address of the contact person  # noqa: E501

        :param contact_person_email: The contact_person_email of this HotelsBody.
        :type contact_person_email: str
        """

        self._contact_person_email = contact_person_email

    @property
    def contact_person_phone(self) -> str:
        """Gets the contact_person_phone of this HotelsBody.

        The phone number of the contact person  # noqa: E501

        :return: The contact_person_phone of this HotelsBody.
        :rtype: str
        """
        return self._contact_person_phone

    @contact_person_phone.setter
    def contact_person_phone(self, contact_person_phone: str):
        """Sets the contact_person_phone of this HotelsBody.

        The phone number of the contact person  # noqa: E501

        :param contact_person_phone: The contact_person_phone of this HotelsBody.
        :type contact_person_phone: str
        """

        self._contact_person_phone = contact_person_phone

    @property
    def contact_person_fax(self) -> str:
        """Gets the contact_person_fax of this HotelsBody.

        The fax number of the contact person  # noqa: E501

        :return: The contact_person_fax of this HotelsBody.
        :rtype: str
        """
        return self._contact_person_fax

    @contact_person_fax.setter
    def contact_person_fax(self, contact_person_fax: str):
        """Sets the contact_person_fax of this HotelsBody.

        The fax number of the contact person  # noqa: E501

        :param contact_person_fax: The contact_person_fax of this HotelsBody.
        :type contact_person_fax: str
        """

        self._contact_person_fax = contact_person_fax

    @property
    def hotel_address_name(self) -> str:
        """Gets the hotel_address_name of this HotelsBody.

        The name of the hotel address  # noqa: E501

        :return: The hotel_address_name of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_name

    @hotel_address_name.setter
    def hotel_address_name(self, hotel_address_name: str):
        """Sets the hotel_address_name of this HotelsBody.

        The name of the hotel address  # noqa: E501

        :param hotel_address_name: The hotel_address_name of this HotelsBody.
        :type hotel_address_name: str
        """

        self._hotel_address_name = hotel_address_name

    @property
    def hotel_address_country_region_code(self) -> str:
        """Gets the hotel_address_country_region_code of this HotelsBody.

        The country/region code of the hotel address  # noqa: E501

        :return: The hotel_address_country_region_code of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_country_region_code

    @hotel_address_country_region_code.setter
    def hotel_address_country_region_code(self, hotel_address_country_region_code: str):
        """Sets the hotel_address_country_region_code of this HotelsBody.

        The country/region code of the hotel address  # noqa: E501

        :param hotel_address_country_region_code: The hotel_address_country_region_code of this HotelsBody.
        :type hotel_address_country_region_code: str
        """

        self._hotel_address_country_region_code = hotel_address_country_region_code

    @property
    def hotel_address_language_code(self) -> str:
        """Gets the hotel_address_language_code of this HotelsBody.

        The language code of the hotel address  # noqa: E501

        :return: The hotel_address_language_code of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_language_code

    @hotel_address_language_code.setter
    def hotel_address_language_code(self, hotel_address_language_code: str):
        """Sets the hotel_address_language_code of this HotelsBody.

        The language code of the hotel address  # noqa: E501

        :param hotel_address_language_code: The hotel_address_language_code of this HotelsBody.
        :type hotel_address_language_code: str
        """

        self._hotel_address_language_code = hotel_address_language_code

    @property
    def hotel_address_name2(self) -> str:
        """Gets the hotel_address_name2 of this HotelsBody.

        The second line of the hotel address name  # noqa: E501

        :return: The hotel_address_name2 of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_name2

    @hotel_address_name2.setter
    def hotel_address_name2(self, hotel_address_name2: str):
        """Sets the hotel_address_name2 of this HotelsBody.

        The second line of the hotel address name  # noqa: E501

        :param hotel_address_name2: The hotel_address_name2 of this HotelsBody.
        :type hotel_address_name2: str
        """

        self._hotel_address_name2 = hotel_address_name2

    @property
    def hotel_address_line1(self) -> str:
        """Gets the hotel_address_line1 of this HotelsBody.

        The first line of the hotel address  # noqa: E501

        :return: The hotel_address_line1 of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_line1

    @hotel_address_line1.setter
    def hotel_address_line1(self, hotel_address_line1: str):
        """Sets the hotel_address_line1 of this HotelsBody.

        The first line of the hotel address  # noqa: E501

        :param hotel_address_line1: The hotel_address_line1 of this HotelsBody.
        :type hotel_address_line1: str
        """

        self._hotel_address_line1 = hotel_address_line1

    @property
    def hotel_address_line2(self) -> str:
        """Gets the hotel_address_line2 of this HotelsBody.

        The second line of the hotel address  # noqa: E501

        :return: The hotel_address_line2 of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_line2

    @hotel_address_line2.setter
    def hotel_address_line2(self, hotel_address_line2: str):
        """Sets the hotel_address_line2 of this HotelsBody.

        The second line of the hotel address  # noqa: E501

        :param hotel_address_line2: The hotel_address_line2 of this HotelsBody.
        :type hotel_address_line2: str
        """

        self._hotel_address_line2 = hotel_address_line2

    @property
    def hotel_address_city(self) -> str:
        """Gets the hotel_address_city of this HotelsBody.

        The city of the hotel address  # noqa: E501

        :return: The hotel_address_city of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_city

    @hotel_address_city.setter
    def hotel_address_city(self, hotel_address_city: str):
        """Sets the hotel_address_city of this HotelsBody.

        The city of the hotel address  # noqa: E501

        :param hotel_address_city: The hotel_address_city of this HotelsBody.
        :type hotel_address_city: str
        """

        self._hotel_address_city = hotel_address_city

    @property
    def hotel_address_zip(self) -> str:
        """Gets the hotel_address_zip of this HotelsBody.

        The zip code of the hotel address  # noqa: E501

        :return: The hotel_address_zip of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_zip

    @hotel_address_zip.setter
    def hotel_address_zip(self, hotel_address_zip: str):
        """Sets the hotel_address_zip of this HotelsBody.

        The zip code of the hotel address  # noqa: E501

        :param hotel_address_zip: The hotel_address_zip of this HotelsBody.
        :type hotel_address_zip: str
        """

        self._hotel_address_zip = hotel_address_zip

    @property
    def hotel_address_phone_no(self) -> str:
        """Gets the hotel_address_phone_no of this HotelsBody.

        The phone number of the hotel address  # noqa: E501

        :return: The hotel_address_phone_no of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_phone_no

    @hotel_address_phone_no.setter
    def hotel_address_phone_no(self, hotel_address_phone_no: str):
        """Sets the hotel_address_phone_no of this HotelsBody.

        The phone number of the hotel address  # noqa: E501

        :param hotel_address_phone_no: The hotel_address_phone_no of this HotelsBody.
        :type hotel_address_phone_no: str
        """

        self._hotel_address_phone_no = hotel_address_phone_no

    @property
    def hotel_address_fax_no(self) -> str:
        """Gets the hotel_address_fax_no of this HotelsBody.

        The fax number of the hotel address  # noqa: E501

        :return: The hotel_address_fax_no of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_fax_no

    @hotel_address_fax_no.setter
    def hotel_address_fax_no(self, hotel_address_fax_no: str):
        """Sets the hotel_address_fax_no of this HotelsBody.

        The fax number of the hotel address  # noqa: E501

        :param hotel_address_fax_no: The hotel_address_fax_no of this HotelsBody.
        :type hotel_address_fax_no: str
        """

        self._hotel_address_fax_no = hotel_address_fax_no

    @property
    def hotel_address_email(self) -> str:
        """Gets the hotel_address_email of this HotelsBody.

        The email address of the hotel address  # noqa: E501

        :return: The hotel_address_email of this HotelsBody.
        :rtype: str
        """
        return self._hotel_address_email

    @hotel_address_email.setter
    def hotel_address_email(self, hotel_address_email: str):
        """Sets the hotel_address_email of this HotelsBody.

        The email address of the hotel address  # noqa: E501

        :param hotel_address_email: The hotel_address_email of this HotelsBody.
        :type hotel_address_email: str
        """

        self._hotel_address_email = hotel_address_email

    @property
    def web_portal_enabled(self) -> bool:
        """Gets the web_portal_enabled of this HotelsBody.

        Indicates if the web portal is enabled for the hotel  # noqa: E501

        :return: The web_portal_enabled of this HotelsBody.
        :rtype: bool
        """
        return self._web_portal_enabled

    @web_portal_enabled.setter
    def web_portal_enabled(self, web_portal_enabled: bool):
        """Sets the web_portal_enabled of this HotelsBody.

        Indicates if the web portal is enabled for the hotel  # noqa: E501

        :param web_portal_enabled: The web_portal_enabled of this HotelsBody.
        :type web_portal_enabled: bool
        """

        self._web_portal_enabled = web_portal_enabled

    @property
    def correspondence_type(self) -> str:
        """Gets the correspondence_type of this HotelsBody.

        The correspondence type  # noqa: E501

        :return: The correspondence_type of this HotelsBody.
        :rtype: str
        """
        return self._correspondence_type

    @correspondence_type.setter
    def correspondence_type(self, correspondence_type: str):
        """Sets the correspondence_type of this HotelsBody.

        The correspondence type  # noqa: E501

        :param correspondence_type: The correspondence_type of this HotelsBody.
        :type correspondence_type: str
        """

        self._correspondence_type = correspondence_type

    @property
    def accounting_contact(self) -> str:
        """Gets the accounting_contact of this HotelsBody.

        The accounting contact  # noqa: E501

        :return: The accounting_contact of this HotelsBody.
        :rtype: str
        """
        return self._accounting_contact

    @accounting_contact.setter
    def accounting_contact(self, accounting_contact: str):
        """Sets the accounting_contact of this HotelsBody.

        The accounting contact  # noqa: E501

        :param accounting_contact: The accounting_contact of this HotelsBody.
        :type accounting_contact: str
        """

        self._accounting_contact = accounting_contact

    @property
    def deduction_type(self) -> str:
        """Gets the deduction_type of this HotelsBody.

        The deduction type  # noqa: E501

        :return: The deduction_type of this HotelsBody.
        :rtype: str
        """
        return self._deduction_type

    @deduction_type.setter
    def deduction_type(self, deduction_type: str):
        """Sets the deduction_type of this HotelsBody.

        The deduction type  # noqa: E501

        :param deduction_type: The deduction_type of this HotelsBody.
        :type deduction_type: str
        """

        self._deduction_type = deduction_type

    @property
    def tenant(self) -> str:
        """Gets the tenant of this HotelsBody.

        The tenant name  # noqa: E501

        :return: The tenant of this HotelsBody.
        :rtype: str
        """
        return self._tenant

    @tenant.setter
    def tenant(self, tenant: str):
        """Sets the tenant of this HotelsBody.

        The tenant name  # noqa: E501

        :param tenant: The tenant of this HotelsBody.
        :type tenant: str
        """

        self._tenant = tenant
